version: '3.1'
services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./templates:/app/templates

networks:
  default:

